#!/bin/bash 
# COPYRIGHT (C) 2008-2012 SERVICEMESH, INC.  ALL RIGHTS RESERVED.  CONFIDENTIAL
# AND PROPRIETARY.

# ALL SOFTWARE, INFORMATION AND ANY OTHER RELATED COMMUNICATIONS (COLLECTIVELY,
# "WORKS") ARE CONFIDENTIAL AND PROPRIETARY INFORMATION THAT ARE THE EXCLUSIVE
# PROPERTY OF SERVICEMESH.  ALL WORKS ARE PROVIDED UNDER THE APPLICABLE
# AGREEMENT OR END USER LICENSE AGREEMENT IN EFFECT BETWEEN YOU AND
# SERVICEMESH.  UNLESS OTHERWISE SPECIFIED IN THE APPLICABLE AGREEMENT, ALL
# WORKS ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESSED OR
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.  ALL USE, DISCLOSURE
# AND/OR REPRODUCTION OF WORKS NOT EXPRESSLY AUTHORIZED BY SERVICEMESH IS
# STRICTLY PROHIBITED.
PATH=$PATH:/sbin:/usr/sbin
export PATH

#check to see if the root user is running the script. If yes, unset SUDO 
        uid=`id | sed -e 's;^.*uid=;;' -e 's;\([0-9]\)(.*;\1;'`
        if [ "$uid" = "0" ] ; then
                SUDO=" "
        else 
                SUDO=`which sudo 2&gt;/dev/null`
                if [ -z "$SUDO" ] ; then
                        echo "ERROR sudo not found!"
                        exit 1
                fi

        fi

#
# Remove gmond and gmetd if they exist on the system
#

if [ -f /etc/init.d/gmond ] ; then
    $SUDO /sbin/service gmond stop &gt;/dev/null 2&gt;&amp;1
    $SUDO /sbin/chkconfig gmod off &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm /etc/init.d/gmond &gt;/dev/null 2&gt;&amp;1
    $SUDO /usr/bin/find /etc -name '*gmond' -exec /bin/rm -rf '{}' \; 
    $SUDO rm -rf /usr/include/ganglia.h &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm -rf /usr/include/ganglia_gexec.h &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm -rf /usr/bin/ganglia-config &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm -rf /usr/lib/ganglia &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm -rf /etc/gmond.conf &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm -rf /usr/sbin/gmond  &gt;/dev/null 2&gt;&amp;1
fi
if [ -f /etc/init.d/gmetad ] ; then
    $SUDO /sbin/service gmetad stop &gt;/dev/null 2&gt;&amp;1
    $SUDO /sbin/chkconfig gmetad off &gt;/dev/null 2&gt;&amp;1
    $SUDO /bin/rm /etc/init.d/gmetad 
    $SUDO /usr/bin/find /etc -name '*gmetad' -exec /bin/rm -rf '{}' \; 
    $SUDO /bin/rm -rf /usr/sbin/gmetad  &gt;/dev/null 2&gt;&amp;1
fi


#
# collectd
#

if [ -d /opt/collectd ];
then
    $SUDO /etc/init.d/collectd stop
    $SUDO chkconfig --del collectd &gt;/dev/null 2&gt;&amp;1
    $SUDO rm -rf /opt/collectd*
fi

if [[ "$AGILITY_OPERATING_SYSTEM" =~ "Ubuntu" ]] ; then 
    # Change to Ubuntu Collectd 10.2 Archive
        ARCHIVE=$HOME/collectd-4.10.2-ubuntu.tgz
else
    # Default is RHEL 4.10.9 Archive
        ARCHIVE=$HOME/collectd-4.10.9-rhel.tgz
fi

if [ -e $ARCHIVE ] ; then
    cd $HOME 
    $SUDO tar -zxf $ARCHIVE
    $SUDO rm $ARCHIVE
else
    echo "Collectd $ARCHIVE file  not found!"
    exit 1 
fi
ARCH=`uname -i`
OSVER=`uname -a`
RHEL6='^.*\.(el6).*'
    case $ARCH in
        i386)
            if [[ "$AGILITY_OPERATING_SYSTEM" =~ "Ubuntu" ]] ; then 
                # Change to Ubuntu Packages
                PACKAGE=*.deb
                PACKAGE_DIR=collectd-4.10.1-ubuntu/collectd_4.10.1_i386/
                COMMAND=dpkg
            else
                # Default is RHEL Packages
                PACKAGE=*.rpm
                if [[ $OSVER =~ $RHEL6 ]]; then
                    PACKAGE_DIR=collectd-4.10.9-rhel/collectd-4.10.9-el6-i386/
                else
                    PACKAGE_DIR=collectd-4.10.9-rhel/collectd-4.10.9-el5-i386/
                fi
                FORCE=--force
                COMMAND=rpm
            fi
        ;;
        x86_64)
            if [[ "$AGILITY_OPERATING_SYSTEM" =~ "Ubuntu" ]] ; then 
                # Change to Ubuntu Packages
                PACKAGE=*.deb
                PACKAGE_DIR=collectd-4.10.1-ubuntu/collectd_4.10.1_amd64/
                COMMAND=dpkg
            else
                # Default is RHEL Package
                PACKAGE=*.rpm
                if [[ $OSVER =~ $RHEL6 ]]; then
                    PACKAGE_DIR=collectd-4.10.9-rhel/collectd-4.10.9-el6-x86_64/
                else
                    PACKAGE_DIR=collectd-4.10.9-rhel/collectd-4.10.9-el5-x86_64/
                fi
                FORCE=--force
                COMMAND=rpm
            fi  

        ;;
        *)
            echo "=================================="
            echo "Unsupported hardware platform $ARCH"
            echo "=================================="
            exit 1 
        ;;
    esac
    
FILETEST=`ls $HOME/$PACKAGE_DIR$PACKAGE`

if [ $? -ne "0" ] ; then
    echo "Install $PACKAGE_DIR$PACKAGE not Found"
    exit 1 
else
    cd $HOME
    $SUDO $COMMAND -i $FORCE $PACKAGE_DIR$PACKAGE
fi
$SUDO chmod 755 /etc/init.d/collectd
$SUDO chkconfig --add collectd &gt;/dev/null 2&gt;&amp;1
$SUDO chkconfig collectd on &gt;/dev/null 2&gt;&amp;1
