#!/bin/bash 
# COPYRIGHT (C) 2008-2012 SERVICEMESH, INC.  ALL RIGHTS RESERVED.  CONFIDENTIAL
# AND PROPRIETARY.

# ALL SOFTWARE, INFORMATION AND ANY OTHER RELATED COMMUNICATIONS (COLLECTIVELY,
# "WORKS") ARE CONFIDENTIAL AND PROPRIETARY INFORMATION THAT ARE THE EXCLUSIVE
# PROPERTY OF SERVICEMESH.  ALL WORKS ARE PROVIDED UNDER THE APPLICABLE
# AGREEMENT OR END USER LICENSE AGREEMENT IN EFFECT BETWEEN YOU AND
# SERVICEMESH.  UNLESS OTHERWISE SPECIFIED IN THE APPLICABLE AGREEMENT, ALL
# WORKS ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND EITHER EXPRESSED OR
# IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.  ALL USE, DISCLOSURE
# AND/OR REPRODUCTION OF WORKS NOT EXPRESSLY AUTHORIZED BY SERVICEMESH IS
# STRICTLY PROHIBITED.
PATH=$PATH:/sbin:/usr/sbin
export PATH

CONFIG=/opt/announce/config.sh

#check to see if the root user is running the script. If yes, unset SUDO 
        uid=`id | sed -e 's;^.*uid=;;' -e 's;\([0-9]\)(.*;\1;'`
        if [ "$uid" = "0" ] ; then
                SUDO=" "
        else 
                SUDO=`which sudo 2&gt;/dev/null`
                if [ -z "$SUDO" ] ; then
                        echo "ERROR sudo not found!"
                        exit 1
                fi

        fi

$SUDO mkdir -p /opt/announce
if [ $? -ne 0 ] ; then
  echo "Failed to create /opt/announce directory" 1&gt;&amp;2
  exit 1
fi


misconfigured=0
if [ -z "${Manager.Protocol}" ] 
then
  echo "AgilityManager.Protocol property is not set." 1&gt;&amp;2
  misconfigured=1
fi

if [ -z "${Manager.Address}" ] 
then
  echo "AgilityManager.Address property is not set." 1&gt;&amp;2
  misconfigured=1
fi

if [ -z "${Manager.Port}" ] 
then
  echo "AgilityManager.Port property is not set." 1&gt;&amp;2
  misconfigured=1
fi

if [ $misconfigured -eq 1 ] 
then
  exit 1
fi

$SUDO echo "URL=${Manager.Protocol}://${Manager.Address}:${Manager.Port}/agility/instance/announce-startup.jsp" | $SUDO tee  $CONFIG &gt;/dev/null
$SUDO echo "UUID=${Instance.UUID}" | $SUDO tee -a  $CONFIG &gt;/dev/null

$SUDO chown root $CONFIG
$SUDO chmod 600 $CONFIG

echo "Startup notifications will be delivered to ${Manager.Protocol}://${Manager.Address}:${Manager.Port}"
echo "Successfully configured announce script" 
